# Benchmark Dataset Configurations

image_benchmark_size: 10000
video_benchmark_size: 5000

image:
  - name: gasstation-generated-images
    path: gasstation/generated-images
    modality: image
    media_type: synthetic
    images_per_parquet: -1
    parquet_per_dataset: -1

  - name: megalith-10m
    path: drawthingsai/megalith-10m
    modality: image
    media_type: real
    source_format: tar
    images_per_parquet: 200
    parquet_per_dataset: 5

  - name: eidon-image
    path: bitmind/bm-eidon-image
    modality: image
    media_type: real
    images_per_parquet: -1
    parquet_per_dataset: -1

  - name: celeb-a-hq
    path: bitmind/celeb-a-hq
    modality: image
    media_type: real
    images_per_parquet: 200
    parquet_per_dataset: 5

  - name: ffhq-256
    path: bitmind/ffhq-256
    modality: image
    media_type: real
    images_per_parquet: 200
    parquet_per_dataset: 5

  - name: ms-coco-unique
    path: bitmind/MS-COCO-unique-256
    modality: image
    media_type: real
    images_per_parquet: 200
    parquet_per_dataset: 5

  - name: journeydb
    path: bitmind/JourneyDB
    modality: image
    media_type: synthetic
    images_per_parquet: 200
    parquet_per_dataset: 5

  - name: genimage-midjourney
    path: bitmind/GenImage_MidJourney
    modality: image
    media_type: synthetic
    images_per_parquet: 100
    parquet_per_dataset: 10

  - name: aura-imagegen
    path: bitmind/bm-aura-imagegen
    modality: image
    media_type: synthetic
    images_per_parquet: 200
    parquet_per_dataset: 5

  - name: imagine-grok
    path: bitmind/bm-imagine
    modality: image
    media_type: synthetic
    source_format: jpg
    images_per_parquet: 200
    parquet_per_dataset: 5

  - name: face-swap
    path: bitmind/face-swap
    modality: image
    media_type: semisynthetic
    images_per_parquet: 333
    parquet_per_dataset: 3

  - name: open-image-v7
    path: bitmind/open-image-v7-256
    modality: image
    media_type: real
    images_per_parquet: 200
    parquet_per_dataset: 5

  - name: afhq
    path: bitmind/AFHQ
    modality: image
    media_type: real
    images_per_parquet: 200
    parquet_per_dataset: 5

  - name: lfw
    path: bitmind/lfw
    modality: image
    media_type: real
    images_per_parquet: 200
    parquet_per_dataset: 5

  - name: caltech-256
    path: bitmind/caltech-256
    modality: image
    media_type: real
    images_per_parquet: 250
    parquet_per_dataset: 4

  - name: caltech-101
    path: bitmind/caltech-101
    modality: image
    media_type: real
    images_per_parquet: 1000
    parquet_per_dataset: 1

  - name: dtd-textures
    path: bitmind/dtd
    modality: image
    media_type: real
    images_per_parquet: 500
    parquet_per_dataset: 2

  - name: idoc-mugshots
    path: bitmind/idoc-mugshots-images
    modality: image
    media_type: real
    images_per_parquet: 200
    parquet_per_dataset: 5

video:
  - name: gasstation-generated-videos
    path: gasstation/generated-videos
    modality: video
    media_type: synthetic
    source_format: zip
    videos_per_zip: -1
    zips_per_dataset: -1

  - name: eidon-video
    path: bitmind/bm-eidon-video
    modality: video
    media_type: real
    source_format: zip
    videos_per_zip: -1
    zips_per_dataset: -1

  - name: imagenet-vidvrd
    path: shangxd/imagenet-vidvrd
    modality: video
    media_type: real
    source_format: zip
    videos_per_zip: 500
    zips_per_dataset: 2

  - name: pe-video
    path: facebook/PE-Video
    modality: video
    media_type: real
    source_format: tar
    videos_per_zip: 500
    zips_per_dataset: 2

  - name: veo3-preferences
    path: Rapidata/text-2-video-human-preferences-veo3
    modality: video
    media_type: synthetic
    source_format: mp4
    videos_per_zip: -1
    zips_per_dataset: -1

  - name: veo2-preferences
    path: Rapidata/text-2-video-human-preferences-veo2
    modality: video
    media_type: synthetic
    source_format: mp4
    videos_per_zip: -1
    zips_per_dataset: -1

  - name: aura-video
    path: bitmind/aura-video
    modality: video
    media_type: synthetic
    source_format: parquet
    videos_per_zip: -1
    zips_per_dataset: -1

  - name: aislop-videos
    path: bitmind/aislop-videos
    modality: video
    media_type: synthetic
    source_format: tar
    videos_per_zip: 200
    zips_per_dataset: 5

  - name: semisynthetic-video
    path: bitmind/semisynthetic-video
    modality: video
    media_type: semisynthetic
    source_format: zip
    videos_per_zip: 100
    zips_per_dataset: 10

