# Benchmark Dataset Configurations

image_benchmark_size: 0
video_benchmark_size: 100000


video:
  - name: holdout-set-ai
    path: bitmind/video-holdout
    modality: video
    media_type: synthetic
    source_format: zip
    videos_per_zip: -1
    zips_per_dataset: -1
    include_paths: ["ai"]

  - name: holdout-set-real
    path: bitmind/video-holdout
    modality: video
    media_type: real
    source_format: zip
    videos_per_zip: -1
    zips_per_dataset: -1
    include_paths: ["real"]