# Benchmark Dataset Configurations

image_benchmark_size: 10000
video_benchmark_size: 5000

image:
  - name: gasstation-generated-images
    path: gasstation/generated-images
    modality: image
    media_type: synthetic
    images_per_parquet: -1
    parquet_per_dataset: -1

  - name: ideogram-25k
    path: terminusresearch/ideogram-25k
    modality: image
    media_type: synthetic
    images_per_parquet: 200
    parquet_per_dataset: 5

  - name: Dalle-3-1M
    path: bitmind/Dalle-3-1M
    modality: image
    media_type: synthetic
    images_per_parquet: 200
    parquet_per_dataset: 5

  - name: SFHQ-part1
    path: bitmind/SyntheticFacesHQ
    modality: image
    media_type: synthetic
    images_per_parquet: 1000
    parquet_per_dataset: 1
    include_paths: ["SFHQ-part1.zip"]

  - name: SFHQ-part2
    path: bitmind/SyntheticFacesHQ
    modality: image
    media_type: synthetic
    images_per_parquet: 1000
    parquet_per_dataset: 1
    include_paths: ["SFHQ-part2.zip"]

  - name: SFHQ-part3
    path: bitmind/SyntheticFacesHQ
    modality: image
    media_type: synthetic
    images_per_parquet: 1000
    parquet_per_dataset: 1
    include_paths: ["SFHQ-part3.zip"]

  - name: SFHQ-part4
    path: bitmind/SyntheticFacesHQ
    modality: image
    media_type: synthetic
    images_per_parquet: 1000
    parquet_per_dataset: 1
    include_paths: ["SFHQ-part4.zip"]

  - name: leonardo-stablecog
    path: bitmind/Deepfake-leonardo-stablecog
    modality: image
    media_type: synthetic
    images_per_parquet: 250
    parquet_per_dataset: 4
    
  - name: fashionpedia
    path: detection-datasets/fashionpedia
    modality: image
    media_type: real
    source_format: parquet
    images_per_parquet: 1000
    parquet_per_dataset: 1

  - name: megalith-10m
    path: drawthingsai/megalith-10m
    modality: image
    media_type: real
    source_format: tar
    images_per_parquet: 500
    parquet_per_dataset: 2

  - name: eidon-image
    path: bitmind/bm-eidon-image
    modality: image
    media_type: real
    images_per_parquet: -1
    parquet_per_dataset: -1

  - name: celeb-a-hq
    path: bitmind/celeb-a-hq
    modality: image
    media_type: real
    images_per_parquet: 200
    parquet_per_dataset: 5

  - name: ffhq-256
    path: bitmind/ffhq-256
    modality: image
    media_type: real
    images_per_parquet: 200
    parquet_per_dataset: 5

  - name: ms-coco-unique
    path: bitmind/MS-COCO-unique-256
    modality: image
    media_type: real
    images_per_parquet: 200
    parquet_per_dataset: 5

  - name: journeydb
    path: bitmind/JourneyDB
    modality: image
    media_type: synthetic
    images_per_parquet: 200
    parquet_per_dataset: 5

  - name: genimage-midjourney
    path: bitmind/GenImage_MidJourney
    modality: image
    media_type: synthetic
    images_per_parquet: 100
    parquet_per_dataset: 10

  - name: aura-imagegen
    path: bitmind/bm-aura-imagegen
    modality: image
    media_type: synthetic
    images_per_parquet: 200
    parquet_per_dataset: 5

  - name: imagine-grok
    path: bitmind/bm-imagine
    modality: image
    media_type: synthetic
    source_format: jpg
    images_per_parquet: 200
    parquet_per_dataset: 5

  - name: face-swap
    path: bitmind/face-swap
    modality: image
    media_type: semisynthetic
    images_per_parquet: 333
    parquet_per_dataset: 3

  - name: open-image-v7
    path: bitmind/open-image-v7-256
    modality: image
    media_type: real
    images_per_parquet: 200
    parquet_per_dataset: 5

  - name: afhq
    path: bitmind/AFHQ
    modality: image
    media_type: real
    images_per_parquet: 200
    parquet_per_dataset: 5

  - name: lfw
    path: bitmind/lfw
    modality: image
    media_type: real
    images_per_parquet: 200
    parquet_per_dataset: 5

  - name: caltech-256
    path: bitmind/caltech-256
    modality: image
    media_type: real
    images_per_parquet: 250
    parquet_per_dataset: 4

  - name: caltech-101
    path: bitmind/caltech-101
    modality: image
    media_type: real
    images_per_parquet: 1000
    parquet_per_dataset: 1

  - name: dtd-textures
    path: bitmind/dtd
    modality: image
    media_type: real
    images_per_parquet: 500
    parquet_per_dataset: 2

  - name: idoc-mugshots
    path: bitmind/idoc-mugshots-images
    modality: image
    media_type: real
    images_per_parquet: 200
    parquet_per_dataset: 5

  - name: klingai-images
    path: bitmind/klingai-images
    modality: image
    media_type: synthetic
    source_format: png
    images_per_parquet: 100
    parquet_per_dataset: 10

  # FakeClue dataset - reorganized with label/category hierarchy
  - name: fakeclue-fake-chameleon
    path: bitmind/FakeClue
    modality: image
    media_type: synthetic
    source_format: zip
    images_per_parquet: 500
    parquet_per_dataset: 2
    include_paths: ["data/fake/chameleon/"]

  - name: fakeclue-fake-doc
    path: bitmind/FakeClue
    modality: image
    media_type: synthetic
    source_format: zip
    images_per_parquet: 500
    parquet_per_dataset: 2
    include_paths: ["data/fake/doc/"]

  - name: fakeclue-fake-ffpp
    path: bitmind/FakeClue
    modality: image
    media_type: synthetic
    source_format: zip
    images_per_parquet: 500
    parquet_per_dataset: 2
    include_paths: ["data/fake/ff++/"]

  - name: fakeclue-fake-genimage
    path: bitmind/FakeClue
    modality: image
    media_type: synthetic
    source_format: zip
    images_per_parquet: 500
    parquet_per_dataset: 2
    include_paths: ["data/fake/genimage/"]

  - name: fakeclue-fake-satellite
    path: bitmind/FakeClue
    modality: image
    media_type: synthetic
    source_format: zip
    images_per_parquet: 500
    parquet_per_dataset: 2
    include_paths: ["data/fake/satellite/"]

  - name: fakeclue-real-doc
    path: bitmind/FakeClue
    modality: image
    media_type: real
    source_format: zip
    images_per_parquet: 500
    parquet_per_dataset: 2
    include_paths: ["data/real/doc/"]

  - name: fakeclue-real-ffpp
    path: bitmind/FakeClue
    modality: image
    media_type: real
    source_format: zip
    images_per_parquet: 500
    parquet_per_dataset: 2
    include_paths: ["data/real/ff++/"]

  - name: fakeclue-real-genimage
    path: bitmind/FakeClue
    modality: image
    media_type: real
    source_format: zip
    images_per_parquet: 500
    parquet_per_dataset: 2
    include_paths: ["data/real/genimage/"]

  - name: fakeclue-real-satellite
    path: bitmind/FakeClue
    modality: image
    media_type: real
    source_format: zip
    images_per_parquet: 500
    parquet_per_dataset: 2
    include_paths: ["data/real/satellite/"]

video:
  - name: gasstation-generated-videos
    path: gasstation/generated-videos
    modality: video
    media_type: synthetic
    source_format: zip
    videos_per_zip: -1
    zips_per_dataset: -1

  - name: eidon-video
    path: bitmind/bm-eidon-video
    modality: video
    media_type: real
    source_format: zip
    videos_per_zip: -1
    zips_per_dataset: -1

  - name: imagenet-vidvrd
    path: shangxd/imagenet-vidvrd
    modality: video
    media_type: real
    source_format: zip
    videos_per_zip: 500
    zips_per_dataset: 2

  - name: pe-video
    path: facebook/PE-Video
    modality: video
    media_type: real
    source_format: tar
    videos_per_zip: 500
    zips_per_dataset: 2

  - name: veo3-preferences
    path: Rapidata/text-2-video-human-preferences-veo3
    modality: video
    media_type: synthetic
    source_format: mp4
    videos_per_zip: -1
    zips_per_dataset: -1

  - name: veo2-preferences
    path: Rapidata/text-2-video-human-preferences-veo2
    modality: video
    media_type: synthetic
    source_format: mp4
    videos_per_zip: -1
    zips_per_dataset: -1

  - name: aura-video
    path: bitmind/aura-video
    modality: video
    media_type: synthetic
    source_format: parquet
    videos_per_zip: -1
    zips_per_dataset: -1

  - name: aislop-videos
    path: bitmind/aislop-videos
    modality: video
    media_type: synthetic
    source_format: tar
    videos_per_zip: 200
    zips_per_dataset: 5

  - name: semisynthetic-video
    path: bitmind/semisynthetic-video
    modality: video
    media_type: semisynthetic
    source_format: zip
    videos_per_zip: 100
    zips_per_dataset: 10
 
  - name: fakeparts-t2v
    path: hi-paris/FakeParts
    modality: video
    media_type: synthetic
    source_format: mp4
    videos_per_zip: 100
    zips_per_dataset: 10
    include_paths: ["t2v/"]
 
  - name: fakeparts-faceswap
    path: hi-paris/FakeParts
    modality: video
    media_type: semisynthetic
    source_format: mp4
    videos_per_zip: 100
    zips_per_dataset: 10
    include_paths: ["faceswap/"]
 
  - name: fakeparts-inpainting
    path: hi-paris/FakeParts
    modality: video
    media_type: semisynthetic
    source_format: mp4
    videos_per_zip: 100
    zips_per_dataset: 10
    include_paths: ["inpainting/"]
 
  - name: fakeparts-outpainting
    path: hi-paris/FakeParts
    modality: video
    media_type: semisynthetic
    source_format: mp4
    videos_per_zip: 100
    zips_per_dataset: 10
    include_paths: ["outpainting/"]
 
  - name: fakeparts-stylechange
    path: hi-paris/FakeParts
    modality: video
    media_type: semisynthetic
    source_format: mp4
    videos_per_zip: 100
    zips_per_dataset: 10
    include_paths: ["stylechange/"]
 
  # DeepAction v1 dataset - split by subdirectory and media type.
  # 2600 total videos, so just take all from each subdir
  - name: deepaction-pexels
    path: faridlab/deepaction_v1
    modality: video
    media_type: real
    source_format: mp4
    videos_per_zip: -1
    zips_per_dataset: -1
    include_paths: ["Pexels/"]
 
  - name: deepaction-bdanimate
    path: faridlab/deepaction_v1
    modality: video
    media_type: synthetic
    source_format: mp4
    videos_per_zip: -1
    zips_per_dataset: -1
    include_paths: ["BDAnimateDiffLightning/"]
 
  - name: deepaction-cogvideox5b
    path: faridlab/deepaction_v1
    modality: video
    media_type: synthetic
    source_format: mp4
    videos_per_zip: -1
    zips_per_dataset: -1
    include_paths: ["CogVideoX5B/"]
 
  - name: deepaction-runwayml
    path: faridlab/deepaction_v1
    modality: video
    media_type: synthetic
    source_format: mp4
    videos_per_zip: -1
    zips_per_dataset: -1
    include_paths: ["RunwayML/"]
 
  - name: deepaction-stablediffusion
    path: faridlab/deepaction_v1
    modality: video
    media_type: synthetic
    source_format: mp4
    videos_per_zip: -1
    zips_per_dataset: -1
    include_paths: ["StableDiffusion/"]
 
  - name: deepaction-veo
    path: faridlab/deepaction_v1
    modality: video
    media_type: synthetic
    source_format: mp4
    videos_per_zip: -1
    zips_per_dataset: -1
    include_paths: ["Veo/"]
 
  - name: deepaction-videopoet
    path: faridlab/deepaction_v1
    modality: video
    media_type: synthetic
    source_format: mp4
    videos_per_zip: -1
    zips_per_dataset: -1
    include_paths: ["VideoPoet/"]

  - name: moviegen-bench
    path: saiyan-world/Goku-MovieGenBench
    modality: video
    media_type: synthetic
    source_format: mp4
    videos_per_zip: -1
    zips_per_dataset: -1

  - name: klingai-videos
    path: bitmind/klingai-videos
    modality: video
    media_type: synthetic
    source_format: mp4
    videos_per_zip: 100
    zips_per_dataset: 10

